CREATE TABLE `comment` ( 
  `comment_ID` INT AUTO_INCREMENT NOT NULL,
  `comment_Content` VARCHAR(255) NOT NULL,
  `user_ID` INT NOT NULL,
  `post_ID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`comment_ID`)
);
CREATE TABLE `post` ( 
  `post_ID` INT AUTO_INCREMENT NOT NULL,
  `post_Content` VARCHAR(255) NOT NULL,
  `post_Name` VARCHAR(255) NOT NULL,
  `user_ID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`post_ID`)
);
CREATE TABLE `user` ( 
  `user_ID` INT AUTO_INCREMENT NOT NULL,
  `full_Name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role` INT(2) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`user_ID`)
);
ALTER TABLE `comment` ADD CONSTRAINT `comment1_ID` FOREIGN KEY (`post_ID`) REFERENCES `post` (`post_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `comment` ADD CONSTRAINT `comment_ID` FOREIGN KEY (`user_ID`) REFERENCES `user` (`user_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `post` ADD CONSTRAINT `post_ID` FOREIGN KEY (`user_ID`) REFERENCES `user` (`user_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
